feat: use geolib to calculate distance
WildCodeSchool/2023-09-orleans-cda-projet2-groupe-c pull request #102
Opened 2024-01-11 21:27 UTC by Mikazian

## Description

Create a custom hook to calculate the distance between two users

## Type of change

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Area of change

- [ ] Frontend
- [ ] Backend
- [ ] Other: .....

## General checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I ran `bun run format`/`bun run lint` before commit
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation where needed
- [ ] My changes generate no new warnings
- [ ] I have checked my code and corrected any misspellings
- [ ] I have updated `develop` and merged to my branch before submitting pull request
- [ ] My pull request generate no conflicts with `develop` branch
- [ ] I requested code review from other team members

## Frontend checklist:

- [ ] I followed guidelines for `HTML`/`JSX`/`Typescript`
- [ ] My `Javascript` generate no new console errors
- [ ] I tested my code cross browsers
- [ ] My slice is pixel perfect for both desktop and mobile according to design
- [ ] I conducted basic QA to assure all features are working
- [ ] I tested responsive for mobile and tablet resolutions

## Backend checklist:

- [ ] I tested admin by manually adding content from zero
- [ ] I created easy to use admin experience which is self-explanatory
- [ ] I added description to admin fields in hard-to-understand areas
- [ ] I followed guidelines for naming `Typescript` variables
- [ ] I conducted basic QA to assure all features are working

2024-01-12 08:53 UTC, ElBarto444 submitted a review, later dismissed

2024-01-12 09:00 UTC, greegouze approved these changes

2024-01-12 11:17 UTC, YDrogen requested changes

2024-01-12 11:17 UTC, YDrogen commented on packages/backend/api/src/user/user-crud.ts
> +      .whereRef('user.city_id', '=', 'city.id')
Pas besoin de cette ligne normalement, c'est déjà fait via le innerJoin

2024-01-12 11:17 UTC, YDrogen commented on packages/frontend/web/src/hooks/use-distance.ts
> +        throw new Error(`Fail to fetch distance: ${String(error)}`);
noooon

2024-01-12 11:17 UTC, YDrogen commented on packages/frontend/web/src/hooks/use-distance.ts
> +export default function useDistance({ ...props }) {
Les props sont pas typées 🩴

2024-01-14 10:13 UTC, Mikazian commented on packages/backend/api/src/user/user-crud.ts
> +      .whereRef('user.city_id', '=', 'city.id')
corrigé

2024-01-14 12:49 UTC, Mikazian commented on packages/frontend/web/src/hooks/use-distance.ts
> +export default function useDistance({ ...props }) {
corrigé

2024-01-15 13:15 UTC, greegouze commented on packages/shared/src/database.ts
> +  coordinates: Point & GeoJson;
Obligé de créer un type GeoJson, pas suffisant avec le type Point, qui est également number, number ?

2024-01-15 13:17 UTC, greegouze approved these changes

2024-01-15 13:17 UTC, greegouze commented on packages/shared/src/index.ts
> +export interface UserBody {
Je l'aurais mis dans un fichier exemple Pref-validations pour garder la cohérence de notre architecture actuelle avec seulement les export dans index

2024-01-15 15:21 UTC, ElBarto444 approved these changes

2024-01-22 09:47 UTC, YDrogen commented on packages/shared/src/database.ts
> +  coordinates: Point & GeoJson;
Bonne question

2024-01-22 10:05 UTC, Mikazian commented on packages/shared/src/database.ts
> +  coordinates: Point & GeoJson;
Oui car JsonObjectFrom et JsonArrayFrom pour les type Point, il créé un format GeoJson. Et comme je récupère les coordinates dans un JsonObjectFrom, il convertis les coordinates en GeoJson

2024-01-22 10:08 UTC, Mikazian commented on packages/shared/src/index.ts
> +export interface UserBody {
J'ai créé un fichier user.ts et j'ai déporté mon code.

2024-01-22 10:10 UTC, Mikazian commented on packages/shared/src/database.ts
> +  coordinates: Point & GeoJson;
J'ai fais des test, dans un select classique je récupère bien :
`coordinates : { x: number, y: number }`

et dans une JsonObject j'obtiens : 
`coordinates : [ number, number ]`

2024-01-22 10:22 UTC, Mikazian commented on packages/frontend/web/src/hooks/use-distance.ts
> +        throw new Error(`Fail to fetch distance: ${String(error)}`);
retirer

2024-01-22 11:17 UTC, greegouze submitted a review, later dismissed

2024-01-22 14:27 UTC, YDrogen commented on packages/shared/src/database.ts
> +  coordinates: Point & GeoJson;
Le problème est que le type `GeoJson` est un objet
Du coup niveau type ça donne
![image](https://github.com/WildCodeSchool/2023-09-orleans-cda-projet2-groupe-c/assets/13053644/cf7e4203-39ec-420f-a813-ec74cfd9f7e9)

2024-01-22 16:13 UTC, Mikazian commented on packages/shared/src/database.ts
> +  coordinates: Point & GeoJson;
corrigé

2024-01-22 16:20 UTC, greegouze submitted a review, later dismissed

2024-01-22 16:23 UTC, greegouze submitted a review, later dismissed

2024-01-26 10:03 UTC, greegouze approved these changes

2024-01-29 15:04 UTC, greegouze approved these changes

2024-01-29 16:21 UTC, YDrogen approved these changes

2024-01-29 16:21 UTC, merged