feat: create backend filter
WildCodeSchool/2023-09-orleans-cda-projet2-groupe-c pull request #103
Opened 2024-01-13 16:56 UTC by Mikazian

## Description

- Create a new migration for create a new table 'preference'
- Add new where clause in the SELECT users to matching with the user's preferences
- Create a PUT route to update user's preferences
- Add to GET route users the logic to display the list of user with matching logic
- Create middlewares to get the user's preference and filter

## Type of change

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Area of change

- [ ] Frontend
- [ ] Backend
- [ ] Other: .....

## General checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I ran `bun run format`/`bun run lint` before commit
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation where needed
- [ ] My changes generate no new warnings
- [ ] I have checked my code and corrected any misspellings
- [ ] I have updated `develop` and merged to my branch before submitting pull request
- [ ] My pull request generate no conflicts with `develop` branch
- [ ] I requested code review from other team members

## Frontend checklist:

- [ ] I followed guidelines for `HTML`/`JSX`/`Typescript`
- [ ] My `Javascript` generate no new console errors
- [ ] I tested my code cross browsers
- [ ] My slice is pixel perfect for both desktop and mobile according to design
- [ ] I conducted basic QA to assure all features are working
- [ ] I tested responsive for mobile and tablet resolutions

## Backend checklist:

- [ ] I tested admin by manually adding content from zero
- [ ] I created easy to use admin experience which is self-explanatory
- [ ] I added description to admin fields in hard-to-understand areas
- [ ] I followed guidelines for naming `Typescript` variables
- [ ] I conducted basic QA to assure all features are working

2024-01-15 13:10 UTC, greegouze commented on packages/shared/src/preference.ts
> +  language_pref_id: z.number().int().positive(),
pourquoi distance nonnegative, et languages_pref_id positive ? positive pour distance ne fonctionne pas ?

2024-01-15 13:10 UTC, greegouze approved these changes

2024-01-15 15:22 UTC, ElBarto444 submitted a review, later dismissed

2024-01-22 11:20 UTC, greegouze approved these changes

2024-01-23 13:10 UTC, greegouze approved these changes

2024-01-29 22:25 UTC, greegouze approved these changes

2024-01-31 15:21 UTC, YDrogen requested changes

2024-01-31 15:21 UTC, YDrogen commented on packages/backend/api/src/middlewares/filter-handlers.ts
C'est pas un middleware ça, ça serait plus un service

2024-01-31 15:21 UTC, YDrogen commented on packages/backend/api/src/middlewares/user-handlers.ts
idem pas un middleware

2024-01-31 15:21 UTC, YDrogen commented on packages/backend/api/src/user/user-crud.ts
> +  filteredUsersByDistance,
C'est pas censé être trop utilisé comme middleware
Conception un peu étrange

2024-01-31 15:38 UTC, Mikazian commented on packages/backend/api/package.json
> +    "@app/shared": "workspace:*",
bun run lint && bun run format, j'ai rien touché ici

2024-01-31 19:44 UTC, Mikazian commented on packages/backend/migrations/src/migrations/20240112083058-database-structure.ts
J'ai opté pour la 2e solution, les enlevé preference_id de la table user et mis user_id dans la table preference puis j'ai ajusté les données préférences du dossier forge

2024-01-31 22:19 UTC, Mikazian commented on packages/backend/api/src/middlewares/filter-handlers.ts
J'ai supprimé le middleware pour le transformer en service

2024-01-31 22:19 UTC, Mikazian commented on packages/backend/api/src/middlewares/user-handlers.ts
J'ai supprimé le middleware pour le transformer en service

2024-01-31 22:19 UTC, Mikazian commented on packages/backend/api/src/user/user-crud.ts
> +  filteredUsersByDistance,
C'est retiré, j'appelle les services à l'intérieur des routes

2024-02-01 18:27 UTC, greegouze approved these changes

2024-02-05 10:36 UTC, YDrogen approved these changes

2024-02-05 10:36 UTC, merged