Feature/user like
WildCodeSchool/2023-09-orleans-cda-projet2-groupe-c pull request #105
Opened 2024-01-20 13:32 UTC by Mikazian

## Description

Please include a summary of the change or which issue is fixed.

## Type of change

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Area of change

- [ ] Frontend
- [ ] Backend
- [ ] Other: .....

## General checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I ran `bun run format`/`bun run lint` before commit
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation where needed
- [ ] My changes generate no new warnings
- [ ] I have checked my code and corrected any misspellings
- [ ] I have updated `develop` and merged to my branch before submitting pull request
- [ ] My pull request generate no conflicts with `develop` branch
- [ ] I requested code review from other team members

## Frontend checklist:

- [ ] I followed guidelines for `HTML`/`JSX`/`Typescript`
- [ ] My `Javascript` generate no new console errors
- [ ] I tested my code cross browsers
- [ ] My slice is pixel perfect for both desktop and mobile according to design
- [ ] I conducted basic QA to assure all features are working
- [ ] I tested responsive for mobile and tablet resolutions

## Backend checklist:

- [ ] I tested admin by manually adding content from zero
- [ ] I created easy to use admin experience which is self-explanatory
- [ ] I added description to admin fields in hard-to-understand areas
- [ ] I followed guidelines for naming `Typescript` variables
- [ ] I conducted basic QA to assure all features are working

2024-01-22 11:16 UTC, greegouze submitted a review, later dismissed

2024-01-23 13:14 UTC, greegouze submitted a review, later dismissed

2024-02-12 14:19 UTC, greegouze submitted a review, later dismissed

2024-02-13 11:02 UTC, YDrogen requested changes

2024-02-13 11:02 UTC, YDrogen commented on packages/frontend/web/src/contexts/UsersInteractionsContext.tsx
> +      userId: Number(userId),
Pourquoi t'envoie le userId ? C'est déjà dans les cookies

2024-02-13 14:23 UTC, Mikazian commented on packages/frontend/web/src/contexts/UsersInteractionsContext.tsx
> +      userId: Number(userId),
J'ai retiré les userId uniquement sur cette PR. Je ferai un fix pour retirer les autres userId

2024-02-14 09:17 UTC, greegouze submitted a review, later dismissed

2024-02-14 09:47 UTC, YDrogen commented on packages/frontend/web/src/pages/Home.tsx
> +            </SidebarLayout>
Pourquoi t'as une Sidebar dans une sidebar ?

2024-02-14 10:41 UTC, Mikazian commented on packages/frontend/web/src/pages/Home.tsx
> +            </SidebarLayout>
corrigé

2024-02-14 11:31 UTC, greegouze approved these changes

2024-02-15 08:10 UTC, YDrogen approved these changes

2024-02-15 08:10 UTC, merged