Feature/frontend filter
WildCodeSchool/2023-09-orleans-cda-projet2-groupe-c pull request #110
Opened 2024-02-07 19:25 UTC by Mikazian

## Description

Please include a summary of the change or which issue is fixed.

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Area of change

- [x] Frontend
- [ ] Backend
- [ ] Other: .....

## General checklist:

- [x] My code follows the style guidelines of this project
- [x] I ran `bun run format`/`bun run lint` before commit
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation where needed
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings
- [x] I have updated `develop` and merged to my branch before submitting pull request
- [x] My pull request generate no conflicts with `develop` branch
- [x] I requested code review from other team members

## Frontend checklist:

- [x] I followed guidelines for `HTML`/`JSX`/`Typescript`
- [x] My `Javascript` generate no new console errors
- [x] I tested my code cross browsers
- [x] My slice is pixel perfect for both desktop and mobile according to design
- [x] I conducted basic QA to assure all features are working
- [x] I tested responsive for mobile and tablet resolutions

## Backend checklist:

- [ ] I tested admin by manually adding content from zero
- [ ] I created easy to use admin experience which is self-explanatory
- [ ] I added description to admin fields in hard-to-understand areas
- [ ] I followed guidelines for naming `Typescript` variables
- [ ] I conducted basic QA to assure all features are working

2024-02-07 19:31 UTC, Mikazian commented
J'ai refais un repull une autre branche pour faire un format prettier de mon code car ça marchait pas sur l'autre branche. J'ai close l'autre branche. Bun run format a enlevé les virgules des fichier ts.config et les modifications demandées ont étés apportés :
- correction : ajouté le cleanup dans use-languages.ts et enlevé la classe vide dans FilterLanguagesForm.tsx

2024-02-07 20:14 UTC, greegouze submitted a review, later dismissed

2024-02-08 09:19 UTC, YDrogen requested changes

2024-02-08 09:19 UTC, YDrogen commented on packages/frontend/web/src/contexts/PreferenceContext.tsx
> +  }, [fetchPreferences]);
cleanup function manquante

2024-02-08 09:19 UTC, YDrogen commented on packages/frontend/web/src/hooks/use-languages.ts
> +      };
À déplacer hors du catch

2024-02-08 11:27 UTC, Mikazian commented on packages/frontend/web/src/contexts/PreferenceContext.tsx
> +  }, [fetchPreferences]);
corrigé

2024-02-08 12:24 UTC, Mikazian commented on packages/frontend/web/src/hooks/use-languages.ts
> +      };
corrigé, j'avais un probleme avec la fonction cleanup j'ai fais une fonction anonyme

2024-02-08 15:49 UTC, greegouze approved these changes

2024-02-09 10:18 UTC, YDrogen requested changes

2024-02-09 10:18 UTC, YDrogen commented on packages/frontend/web/src/contexts/PreferenceContext.tsx
> +  }, [fetchPreferences]);
Non, il manque toujours la cleanup function 🤔

2024-02-09 10:49 UTC, Mikazian commented on packages/frontend/web/src/contexts/PreferenceContext.tsx
> +  }, [fetchPreferences]);
c'est bon il a ajouté

2024-02-09 12:12 UTC, greegouze approved these changes

2024-02-12 08:51 UTC, YDrogen approved these changes

2024-02-12 08:52 UTC, merged