Feature/chat interaction
WildCodeSchool/2023-09-orleans-cda-projet2-groupe-c pull request #116
Opened 2024-02-20 14:32 UTC by greegouze

## Description

Please include a summary of the change or which issue is fixed.

## Type of change

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Area of change

- [ ] Frontend
- [ ] Backend
- [ ] Other: .....

## General checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I ran `bun run format`/`bun run lint` before commit
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation where needed
- [ ] My changes generate no new warnings
- [ ] I have checked my code and corrected any misspellings
- [ ] I have updated `develop` and merged to my branch before submitting pull request
- [ ] My pull request generate no conflicts with `develop` branch
- [ ] I requested code review from other team members

## Frontend checklist:

- [ ] I followed guidelines for `HTML`/`JSX`/`Typescript`
- [ ] My `Javascript` generate no new console errors
- [ ] I tested my code cross browsers
- [ ] My slice is pixel perfect for both desktop and mobile according to design
- [ ] I conducted basic QA to assure all features are working
- [ ] I tested responsive for mobile and tablet resolutions

## Backend checklist:

- [ ] I tested admin by manually adding content from zero
- [ ] I created easy to use admin experience which is self-explanatory
- [ ] I added description to admin fields in hard-to-understand areas
- [ ] I followed guidelines for naming `Typescript` variables
- [ ] I conducted basic QA to assure all features are working

2024-02-21 19:34 UTC, Mikazian commented on packages/backend/api/src/interaction/interaction-crud.ts
> +import type { Conversation } from '@app/shared';
Peut être tous sur la même ligne

2024-02-21 19:34 UTC, Mikazian commented on packages/backend/api/src/interaction/interaction-crud.ts
> +type NewConversation = Omit<Conversation, 'id'>;
Fait plutôt le typage côté shared puis tu importes ce type ici au lieu de le créer ici

2024-02-21 19:34 UTC, Mikazian commented on packages/backend/api/src/user/message.ts
> +
ta un retour à la ligne ici

2024-02-21 19:34 UTC, Mikazian commented on packages/backend/api/src/user/message.ts
> +      const { userId } = req.params;
Number.parseInt

2024-02-21 19:34 UTC, Mikazian commented on packages/backend/api/src/user/message.ts
> +
retirer le retour à la ligne

2024-02-21 19:34 UTC, Mikazian commented on packages/frontend/web/src/components/message/Conversation.tsx
> +  const { register, handleSubmit, reset } = useForm();
zodResolver ?

2024-02-21 19:34 UTC, Mikazian commented on packages/frontend/web/src/components/message/ConversationsList.tsx
> +                          // alt={`Picture of ${conversation.receiver[0].receiver_name}`}
code commenté

2024-02-21 19:34 UTC, Mikazian commented on packages/frontend/web/src/components/message/ConversationsList.tsx
> +                              : ''
undefined

2024-02-21 19:34 UTC, Mikazian commented on packages/frontend/web/src/contexts/ConversationContext.tsx
> +}
beaucoup de typage ici, mettons plutôt la logique du typage dans le dossier shared

2024-02-21 19:34 UTC, Mikazian commented on packages/frontend/web/src/contexts/ConversationContext.tsx
> +  /* const navigate = useNavigate();  */
code commenté

2024-02-21 19:34 UTC, Mikazian commented on packages/frontend/web/src/contexts/ConversationContext.tsx
> +            credentials: 'include',
enlever le cookie

2024-02-21 19:34 UTC, Mikazian commented on packages/frontend/web/src/hooks/use-all-conversations.ts
> +      throw new Error(`Failed to fetch messages: ${String(error)}`);
enlever le throw et créer un state error pour setError

2024-02-21 19:34 UTC, Mikazian commented on packages/frontend/web/src/hooks/use-interactions.ts
> +        throw new Error(`Fail to fetch interactions verify: ${String(error)}`);
pareil enlever le throw

2024-02-21 19:34 UTC, Mikazian commented on packages/frontend/web/src/pages/Home.tsx
> +      userProfile.hobbies.length > 0) */
Code commenté

2024-02-23 08:23 UTC, Mikazian submitted a review, later dismissed

2024-02-26 08:54 UTC, YDrogen requested changes

2024-02-26 10:03 UTC, Mikazian approved these changes

2024-02-26 10:54 UTC, YDrogen approved these changes

2024-02-26 10:54 UTC, merged