feat: add age pref in profile form
WildCodeSchool/2023-09-orleans-cda-projet2-groupe-c pull request #119
Opened 2024-02-23 11:21 UTC by Mikazian

## Description

- Add to the profile form, the age pref form

## Type of change

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Area of change

- [ ] Frontend
- [ ] Backend
- [ ] Other: .....

## General checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I ran `bun run format`/`bun run lint` before commit
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation where needed
- [ ] My changes generate no new warnings
- [ ] I have checked my code and corrected any misspellings
- [ ] I have updated `develop` and merged to my branch before submitting pull request
- [ ] My pull request generate no conflicts with `develop` branch
- [ ] I requested code review from other team members

## Frontend checklist:

- [ ] I followed guidelines for `HTML`/`JSX`/`Typescript`
- [ ] My `Javascript` generate no new console errors
- [ ] I tested my code cross browsers
- [ ] My slice is pixel perfect for both desktop and mobile according to design
- [ ] I conducted basic QA to assure all features are working
- [ ] I tested responsive for mobile and tablet resolutions

## Backend checklist:

- [ ] I tested admin by manually adding content from zero
- [ ] I created easy to use admin experience which is self-explanatory
- [ ] I added description to admin fields in hard-to-understand areas
- [ ] I followed guidelines for naming `Typescript` variables
- [ ] I conducted basic QA to assure all features are working

2024-02-23 13:01 UTC, greegouze approved these changes

2024-02-27 09:36 UTC, greegouze submitted a review, later dismissed

2024-02-27 10:12 UTC, greegouze submitted a review, later dismissed

2024-02-27 11:25 UTC, YDrogen requested changes

2024-02-27 11:25 UTC, YDrogen commented on packages/frontend/web/src/components/forms/FormAge.tsx
> +  });
??? Pourquoi ??

2024-02-27 11:25 UTC, YDrogen commented on packages/frontend/web/src/pages/FormProfile.tsx
> +          await fetchUsers({ signal });
Pourquoi y'en a qu'un en `await` ?

2024-02-27 13:21 UTC, Mikazian commented on packages/frontend/web/src/pages/FormProfile.tsx
> +          await fetchUsers({ signal });
<img width="646" alt="Capture d’écran 2024-02-27 à 14 20 42" src="https://github.com/WildCodeSchool/2023-09-orleans-cda-projet2-groupe-c/assets/120253140/ed779c2c-17e2-4b75-bcf6-f5fdfc68a7a0">

2024-02-27 13:24 UTC, Mikazian commented on packages/frontend/web/src/pages/FormProfile.tsx
> +          await fetchUsers({ signal });
j'ai changé le typage de return en void du coup j'ai retiré les await

2024-02-27 14:17 UTC, Mikazian commented on packages/frontend/web/src/components/forms/FormAge.tsx
> +  });
retiré j'ai créé des inputs cachés

2024-02-27 14:34 UTC, greegouze approved these changes

2024-02-27 15:09 UTC, YDrogen approved these changes

2024-02-27 15:10 UTC, merged