Feature/database
WildCodeSchool/2023-09-orleans-cda-projet2-groupe-c pull request #68
Opened 2023-11-22 16:24 UTC by Mikazian

## Description

Please include a summary of the change or which issue is fixed.

## Type of change

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Area of change

- [ ] Frontend
- [ ] Backend
- [ ] Other: .....

## General checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I ran `bun run format`/`bun run lint` before commit
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation where needed
- [ ] My changes generate no new warnings
- [ ] I have checked my code and corrected any misspellings
- [ ] I have updated `develop` and merged to my branch before submitting pull request
- [ ] My pull request generate no conflicts with `develop` branch
- [ ] I requested code review from other team members

## Frontend checklist:

- [ ] I followed guidelines for `HTML`/`JSX`/`Typescript`
- [ ] My `Javascript` generate no new console errors
- [ ] I tested my code cross browsers
- [ ] My slice is pixel perfect for both desktop and mobile according to design
- [ ] I conducted basic QA to assure all features are working
- [ ] I tested responsive for mobile and tablet resolutions

## Backend checklist:

- [ ] I tested admin by manually adding content from zero
- [ ] I created easy to use admin experience which is self-explanatory
- [ ] I added description to admin fields in hard-to-understand areas
- [ ] I followed guidelines for naming `Typescript` variables
- [ ] I conducted basic QA to assure all features are working

2023-11-23 15:09 UTC, ElBarto444 approved these changes
C'est good

2023-11-24 09:44 UTC, YDrogen requested changes

2023-11-24 09:44 UTC, YDrogen commented on packages/types/src/database.ts
> +}
Si c'est pour faire des `Omit`, autant refaire les définitions
Ça fait plus propre, même si le code est dupliqué

2023-11-28 11:26 UTC, Mikazian commented on packages/types/src/database.ts
> +  gender?: string;
J'aurai créé un type Gender = male | female | non-binary

2023-11-28 14:55 UTC, ElBarto444 submitted a review, later dismissed
Bon travail Grégory

2023-11-29 10:27 UTC, Mikazian commented on packages/backend/migrations/src/migrations/20231122143009-database-structure.ts
> +      .addColumn('hobby_id', 'int2', (col) => col.unsigned())
integer

2023-11-29 12:29 UTC, ElBarto444 approved these changes

2023-11-29 14:21 UTC, YDrogen requested changes

2023-11-29 14:21 UTC, YDrogen commented on packages/types/src/database.ts
> +}
On n'avait pas dit qu'on changeait ?

2023-11-29 14:33 UTC, YDrogen approved these changes

2023-11-29 14:33 UTC, merged