nav bar
WildCodeSchool/2023-09-orleans-cda-projet2-groupe-c pull request #69
Opened 2023-11-24 14:09 UTC by greegouze

## Description

Creating the navigation bar

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Area of change

- [x] Frontend
- [ ] Backend
- [ ] Other: .....

## General checklist:

- [x] My code follows the style guidelines of this project
- [x] I ran `bun run format`/`bun run lint` before commit
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation where needed
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings
- [x] I have updated `develop` and merged to my branch before submitting pull request
- [x] My pull request generate no conflicts with `develop` branch
- [ ] I requested code review from other team members

## Frontend checklist:

- [x] I followed guidelines for `HTML`/`JSX`/`Typescript`
- [x] My `Javascript` generate no new console errors
- [x] I tested my code cross browsers
- [x] My slice is pixel perfect for both desktop and mobile according to design
- [x] I conducted basic QA to assure all features are working
- [x] I tested responsive for mobile and tablet resolutions

## Backend checklist:

- [ ] I tested admin by manually adding content from zero
- [ ] I created easy to use admin experience which is self-explanatory
- [ ] I added description to admin fields in hard-to-understand areas
- [ ] I followed guidelines for naming `Typescript` variables
- [ ] I conducted basic QA to assure all features are working

2023-11-27 15:08 UTC, ElBarto444 commented on packages/frontend/web/src/pages/Home.tsx
Tu as du oublier de renommer le SomeInterface et someData qui étaient là de base, du coup ça fait pas très compréhensible je trouve.

2023-11-28 10:23 UTC, Mikazian commented on packages/frontend/web/src/pages/Home.tsx
> +      <NavBar />
On affiche pas la Navbar dans la home page, il faut créer une page principale ou il y aura la navbar, card etc.
Home sera la page de connexion et de registration

2023-11-28 14:44 UTC, Mikazian submitted a review, later dismissed

2023-11-28 15:00 UTC, ElBarto444 approved these changes
Ok pour moi

2023-11-28 16:02 UTC, YDrogen requested changes

2023-11-28 16:02 UTC, YDrogen commented on packages/frontend/web/src/globals.css
Vous avez déjà oublié comment utiliser `Tailwind` ?
[RTFM](https://tailwindcss.com/docs/adding-custom-styles)

2023-11-29 13:23 UTC, Mikazian approved these changes

2023-11-29 13:24 UTC, Mikazian commented
Bon boulot !

2023-11-29 13:39 UTC, Mikazian approved these changes

2023-11-30 08:56 UTC, ElBarto444 commented on packages/frontend/web/src/components/ThemeSwitcher.tsx
>  import { useEffect, useState } from 'react';
ton useEffect est pas utilisé dans ce fichier

2023-11-30 08:56 UTC, ElBarto444 commented on packages/frontend/web/src/pages/Home.tsx
>  import { useDisclosure } from '@app/frontend-shared';
celui-ci non plus

2023-11-30 09:32 UTC, ElBarto444 approved these changes

2023-12-01 10:30 UTC, YDrogen requested changes

2023-12-01 10:30 UTC, YDrogen commented on packages/frontend/web/src/components/NavBar.tsx
Y'a des boucles qui se perdent !
Trop de répétition de code

2023-12-01 10:30 UTC, YDrogen commented on packages/frontend/web/src/components/icons/DarkIcon.tsx
C'est un dessin de "Dark" ? Ça existe ça le "Dark" ? Ça se mange ?

2023-12-01 10:30 UTC, YDrogen commented on packages/frontend/web/src/components/icons/LightIcon.tsx
C'est un dessin de "Light" ? Ça existe ça le "Light" ? Ça se mange ?

2023-12-01 10:30 UTC, YDrogen commented on packages/frontend/web/src/components/icons/Logo.tsx
`LogoIcon`

2023-12-01 10:30 UTC, YDrogen commented on packages/frontend/web/src/globals.css
> +  }
Un meilleur nom de class est demandé à l'accueil
Les class utilitaires sont faites pour être utilisées n'importe où, pas que sur le logo

2023-12-01 10:30 UTC, YDrogen commented on packages/frontend/web/tailwind.config.js
> +        'light-light': 'var(--light-light)',
C'est quoi comme couleur ça "light" ?

2023-12-04 10:53 UTC, Mikazian commented on packages/frontend/web/src/contexts/ThemeContext.tsx
> +export const useTheme = () => {
Tu peux ajouter cette ligne si tu veux enlever le message warning : 
/* eslint-disable react-refresh/only-export-components */

2023-12-04 14:29 UTC, Mikazian approved these changes

2023-12-06 08:14 UTC, Mikazian approved these changes

2023-12-06 09:00 UTC, ElBarto444 submitted a review, later dismissed
C'est bon pour moi

2023-12-06 09:44 UTC, YDrogen requested changes

2023-12-06 09:44 UTC, YDrogen commented on .eslintrc.cjs
> +      'off',
Non, c'est censé remplacer `'warn'`

2023-12-06 09:44 UTC, YDrogen commented on packages/frontend/web/src/components/ThemeSwitcher.tsx
> +      <SunIcon className='text-secondary scale-sun absolute h-4 w-4 md:h-5 md:w-5' />
Les `scale-` en mode variables sont un peu overkill mais why not
(`scale-0 dark:scale-1` et `scale-1 dark:scale-0` auraient suffit)

2023-12-06 09:44 UTC, YDrogen commented on packages/frontend/web/src/components/NavBar.tsx
> +  };
Pourquoi ne pas mettre ça directement dans `ThemeSwitcher` ?

2023-12-07 08:51 UTC, Mikazian submitted a review, later dismissed

2023-12-07 08:54 UTC, ElBarto444 approved these changes
C'est ok

2023-12-07 09:36 UTC, YDrogen requested changes

2023-12-07 09:36 UTC, YDrogen commented on packages/frontend/web/src/components/NavBar.tsx
> +  ];
À sortir hors du component

2023-12-07 13:38 UTC, Mikazian approved these changes

2023-12-07 13:50 UTC, ElBarto444 approved these changes
C'est ok

2023-12-07 15:01 UTC, merged