Feature/home
WildCodeSchool/2023-09-orleans-cda-projet2-groupe-c pull request #70
Opened 2023-11-28 21:55 UTC by Mikazian

## Description

Please include a summary of the change or which issue is fixed.
- Create Home page for login and registration
- Create button component

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Area of change

- [x] Frontend
- [ ] Backend
- [ ] Other: .....

## General checklist:

- [x] My code follows the style guidelines of this project
- [x] I ran `bun run format`/`bun run lint` before commit
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation where needed
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings
- [x] I have updated `develop` and merged to my branch before submitting pull request
- [x] My pull request generate no conflicts with `develop` branch
- [ ] I requested code review from other team members

## Frontend checklist:

- [x] I followed guidelines for `HTML`/`JSX`/`Typescript`
- [x] My `Javascript` generate no new console errors
- [ ] I tested my code cross browsers
- [x] My slice is pixel perfect for both desktop and mobile according to design
- [ ] I conducted basic QA to assure all features are working
- [x] I tested responsive for mobile and tablet resolutions

## Backend checklist:

- [ ] I tested admin by manually adding content from zero
- [ ] I created easy to use admin experience which is self-explanatory
- [ ] I added description to admin fields in hard-to-understand areas
- [x] I followed guidelines for naming `Typescript` variables
- [ ] I conducted basic QA to assure all features are working

2023-11-29 10:08 UTC, greegouze approved these changes

2023-11-29 20:40 UTC, greegouze commented on packages/frontend/web/src/components/svg/Logo.tsx
> +export default function Logo() {
On a le même nom de de composant 'Logo'

2023-11-30 08:24 UTC, Mikazian commented on packages/frontend/web/src/components/svg/Logo.tsx
> +export default function Logo() {
done

2023-11-30 08:42 UTC, greegouze approved these changes

2023-11-30 09:05 UTC, ElBarto444 submitted a review, later dismissed
C'est good

2023-12-01 11:15 UTC, Mikazian commented on package.json
> +    "framer-motion": "^10.16.5"
done, framer motion a été enlevé du package et ajouté dans le package du front-end/web

2023-12-04 12:21 UTC, greegouze approved these changes

2023-12-06 08:54 UTC, ElBarto444 submitted a review, later dismissed
Ça m'a l'air bon

2023-12-06 11:08 UTC, YDrogen requested changes

2023-12-06 11:08 UTC, YDrogen commented on packages/frontend/web/src/components/Button.tsx
> +      {word}
Pourquoi ne pas utiliser `children` ?

2023-12-06 11:08 UTC, YDrogen commented on packages/frontend/web/src/components/home/RandomSentence.tsx
> +    sentences[Math.floor(Math.random() * sentences.length)];
A sortir hors du component

2023-12-06 11:08 UTC, YDrogen commented on packages/frontend/web/src/components/home/RandomSentence.tsx
> +];
Peut être sorti dans un .json puis importé

2023-12-06 13:44 UTC, Mikazian commented on packages/frontend/web/src/components/home/RandomSentence.tsx
> +];
done

2023-12-06 13:45 UTC, Mikazian commented on packages/frontend/web/src/components/home/RandomSentence.tsx
> +    sentences[Math.floor(Math.random() * sentences.length)];
done

2023-12-06 14:51 UTC, greegouze approved these changes

2023-12-07 09:58 UTC, YDrogen requested changes

2023-12-07 09:58 UTC, YDrogen commented on packages/frontend/web/src/components/home/sentences.json
ce n'est pas un component
`src/data/home-sentences.json` par exemple serait plus approprié

2023-12-07 09:58 UTC, YDrogen commented on packages/frontend/web/tsconfig.json
> +  "include": ["src/**/*", "src/**/*.json"],
`src` ne suffit pas ?

2023-12-07 09:59 UTC, YDrogen requested changes

2023-12-07 09:59 UTC, YDrogen commented on packages/frontend/web/src/components/Button.tsx
> +  readonly children: string;
`children` n'est pas censé être un string

2023-12-07 12:36 UTC, Mikazian commented on packages/frontend/web/src/components/home/sentences.json
done

2023-12-07 12:37 UTC, Mikazian commented on packages/frontend/web/tsconfig.json
> +  "include": ["src/**/*", "src/**/*.json"],
update at "src"

2023-12-07 12:39 UTC, Mikazian commented on packages/frontend/web/src/components/Button.tsx
> +  readonly children: string;
update at React.ReatNode

2023-12-07 13:40 UTC, greegouze submitted a review, later dismissed

2023-12-07 15:07 UTC, YDrogen commented on packages/frontend/web/src/components/home/sentences.json
C'est toujours pas un component 😭

2023-12-07 15:39 UTC, Mikazian commented
conflicts revolved !

2023-12-07 16:07 UTC, ElBarto444 submitted a review, later dismissed
C'est bon pour moi

2023-12-08 08:12 UTC, YDrogen requested changes

2023-12-08 08:12 UTC, YDrogen commented on packages/frontend/web/src/components/Button.tsx
Les balises natives HTML (`button` par exemple) ont des props typées `HTMLButtonElement` ou un truc du genre
Du coup tu peux extends ces props pour garder celles de bases et ajouter les tiennes
```typescript
interface ButtonProps extends HTMLButtonElement {
  readonly isOutline: boolean;
}
```
Ça évite de typer à la main `children` ou `type` dans ton cas ici

2023-12-08 08:55 UTC, greegouze approved these changes

2023-12-08 10:09 UTC, ElBarto444 submitted a review, later dismissed
c'est ok pour moi

2023-12-08 10:16 UTC, YDrogen requested changes
Déso, t'as oublié une conversation non résolue au dessus :(

2023-12-08 10:38 UTC, Mikazian commented
J'ai déplacé le dossier data dans src

2023-12-08 10:39 UTC, greegouze approved these changes

2023-12-08 13:46 UTC, ElBarto444 approved these changes
C'est validé

2023-12-08 14:17 UTC, YDrogen approved these changes

2023-12-08 14:18 UTC, merged