Create login user
WildCodeSchool/2023-09-orleans-cda-projet2-groupe-c pull request #79
Opened 2023-12-04 10:34 UTC by Mikazian

## Description

Please include a summary of the change or which issue is fixed.

## Type of change

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Area of change

- [ ] Frontend
- [ ] Backend
- [ ] Other: .....

## General checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I ran `bun run format`/`bun run lint` before commit
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation where needed
- [ ] My changes generate no new warnings
- [ ] I have checked my code and corrected any misspellings
- [ ] I have updated `develop` and merged to my branch before submitting pull request
- [ ] My pull request generate no conflicts with `develop` branch
- [ ] I requested code review from other team members

## Frontend checklist:

- [ ] I followed guidelines for `HTML`/`JSX`/`Typescript`
- [ ] My `Javascript` generate no new console errors
- [ ] I tested my code cross browsers
- [ ] My slice is pixel perfect for both desktop and mobile according to design
- [ ] I conducted basic QA to assure all features are working
- [ ] I tested responsive for mobile and tablet resolutions

## Backend checklist:

- [ ] I tested admin by manually adding content from zero
- [ ] I created easy to use admin experience which is self-explanatory
- [ ] I added description to admin fields in hard-to-understand areas
- [ ] I followed guidelines for naming `Typescript` variables
- [ ] I conducted basic QA to assure all features are working

2023-12-09 20:08 UTC, greegouze submitted a review, later dismissed

2023-12-13 13:57 UTC, ElBarto444 approved these changes
C'es ok

2023-12-14 09:50 UTC, YDrogen requested changes
Pour les formulaires `react-hook-form` + `zod` tu peux utiliser https://github.com/react-hook-form/resolvers#zod

Dans tous les package.json, il faut vérifier que le package `@app/shared` est bien en `dependencies` et plus en `devDependencies`

2023-12-14 09:50 UTC, YDrogen commented on packages/frontend/web/src/router.tsx
Nope, on utilise la [nouvelle façon](https://reactrouter.com/en/main/routers/picking-a-router) de faire des routes

2023-12-14 09:50 UTC, YDrogen commented on packages/frontend/web/src/pages/Home.tsx
Oula, assigner une variable comme ça, c'est vraiment pas une bonne idée
Tu peux simplement return du JSX dans chaque if
```typescript
if(true) {
  return (
    <div>Coucou</div>
  );
}
```

2023-12-14 09:50 UTC, YDrogen commented on packages/frontend/web/src/components/icons/PasswordVisibleIcon.tsx
Ça ressemble à quoi un icône de mot de passe visible ?

2023-12-14 09:50 UTC, YDrogen commented on packages/frontend/web/src/components/icons/PasswordNotVisibleIcon.tsx
Ça ressemble à quoi un icône de mot de passe invisible ?

2023-12-14 09:50 UTC, YDrogen commented on packages/frontend/web/src/components/home/HomeButtons.tsx
> +      <Link to='/login' className='flex w-full justify-center'>
Tu peux retirer le commentaire au dessus du coup

2023-12-14 09:50 UTC, YDrogen commented on packages/backend/api/src/auth/auth.ts
> +      message: 'JWT is created and User is connected',
L'utilisateur n'a pas à savoir quelle technique de connexion est utilisée
\+ bizarre d'afficher à l'utilisateur "L'utilisateur est connecté"

2023-12-15 08:23 UTC, Mikazian commented on packages/frontend/web/src/pages/Home.tsx
J'ai enlevé la variable let et j'ai return maintenant le contenu dans les block if

2023-12-15 08:23 UTC, Mikazian commented on packages/frontend/web/src/components/icons/PasswordVisibleIcon.tsx
C'est un oeil ouvert

2023-12-15 08:24 UTC, Mikazian commented on packages/frontend/web/src/components/icons/PasswordNotVisibleIcon.tsx
C'est un oeil fermé

2023-12-15 08:24 UTC, Mikazian commented on packages/frontend/web/src/components/home/HomeButtons.tsx
> +      <Link to='/login' className='flex w-full justify-center'>
Commentaire TODO est retiré

2023-12-15 08:28 UTC, Mikazian commented on packages/frontend/web/src/components/auth/Login.tsx
> +  ) : (
J'avais fais un if/else mais ESLint me dit de faire une ternaire.
J'ai remis un if/else et j'ai ajouté un commentaire au dessus pour désactiver la ternaire

2023-12-15 08:29 UTC, Mikazian commented on packages/backend/api/src/auth/auth.ts
> +      message: 'JWT is created and User is connected',
J'ai retiré tous les messages des responses

2023-12-15 08:55 UTC, Mikazian commented on packages/frontend/web/src/router.tsx
J'ai remis la nouvelle méthodes des routers, ce que j'ai fais, j'ai créé un composant  AuthLayout pour pouvoir utiliser mon state isLoggedIn de mon AuthContext  et renvoyer un composant en fonction de si un utilisateur est co ou pas

2023-12-15 16:05 UTC, ElBarto444 submitted a review, later dismissed
Est-ce qu'il faudra qu'on renomme nos dossiers types en shared sur nos prochaines PR ?
Sinon ça m'a l'air good

2023-12-16 10:22 UTC, greegouze submitted a review, later dismissed

2023-12-18 09:06 UTC, YDrogen requested changes

2023-12-18 09:06 UTC, YDrogen commented on packages/frontend/web/src/components/auth/Login.tsx
> +    return (
idem

2023-12-18 09:06 UTC, YDrogen commented on packages/frontend/web/src/components/auth/Login.tsx
> +  }
A descendre en dessous avec les autres if/return

2023-12-18 09:06 UTC, YDrogen commented on packages/frontend/web/src/components/icons/PasswordVisibleIcon.tsx
Pourquoi ne pas l'appeler comme ça dans ce cas ? Un component réutilisable comme un icône doit être nommé en fonction de ce qu'il contient, pas de là où il va être utilisé

2023-12-18 09:58 UTC, Mikazian commented on packages/frontend/web/src/router.tsx
> +
Je crois que c'est corrigé

2023-12-18 10:05 UTC, Mikazian commented on packages/frontend/web/src/pages/Home.tsx
> +    return (
Je crois que c'est corrigé

2023-12-18 10:11 UTC, Mikazian commented on packages/frontend/web/src/components/auth/Login.tsx
> +                    </svg>
C'est converti en composants

2023-12-18 10:12 UTC, Mikazian commented on packages/frontend/web/src/components/auth/Login.tsx
> +    return (
C'est fait

2023-12-18 10:16 UTC, Mikazian commented on packages/frontend/web/src/components/auth/Login.tsx
> +  }
fait

2023-12-18 12:38 UTC, greegouze submitted a review, later dismissed

2023-12-18 15:32 UTC, ElBarto444 approved these changes
ok

2023-12-19 09:51 UTC, YDrogen requested changes

2023-12-19 09:51 UTC, YDrogen commented on packages/frontend/web/src/components/auth/VisiblePassword.tsx
> +import EyeCloneIcon from '../icons/EyeCloseIcon';
Faute d'orthographe ici

2023-12-19 10:46 UTC, Mikazian commented on packages/frontend/web/src/components/auth/VisiblePassword.tsx
> +import EyeCloneIcon from '../icons/EyeCloseIcon';
corrigé !

2023-12-19 10:49 UTC, greegouze approved these changes

2023-12-19 11:16 UTC, ElBarto444 commented on packages/frontend/web/src/components/auth/Login.tsx
> +              <p>{`You don't have an account ?`}</p>
J'aurais plus vu "No account yet ?", ça sonne mieux au niveau de la syntaxe

2023-12-19 11:16 UTC, ElBarto444 commented on packages/frontend/web/src/components/auth/Login.tsx
> +                {`Create now`}
et ici "Create one now"

2023-12-19 12:36 UTC, Mikazian commented on packages/frontend/web/src/components/auth/Login.tsx
> +              <p>{`You don't have an account ?`}</p>
corrigé !

2023-12-19 12:36 UTC, Mikazian commented on packages/frontend/web/src/components/auth/Login.tsx
> +                {`Create now`}
corrigé !

2023-12-19 12:41 UTC, greegouze approved these changes

2023-12-20 10:06 UTC, YDrogen approved these changes

2023-12-20 10:06 UTC, merged