Feature/inscription step 1
WildCodeSchool/2023-09-orleans-cda-projet2-groupe-c pull request #84
Opened 2023-12-09 14:23 UTC by greegouze

## Description

Please include a summary of the change or which issue is fixed.

## Type of change

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Area of change

- [ ] Frontend
- [ ] Backend
- [ ] Other: .....

## General checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I ran `bun run format`/`bun run lint` before commit
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation where needed
- [ ] My changes generate no new warnings
- [ ] I have checked my code and corrected any misspellings
- [ ] I have updated `develop` and merged to my branch before submitting pull request
- [ ] My pull request generate no conflicts with `develop` branch
- [ ] I requested code review from other team members

## Frontend checklist:

- [ ] I followed guidelines for `HTML`/`JSX`/`Typescript`
- [ ] My `Javascript` generate no new console errors
- [ ] I tested my code cross browsers
- [ ] My slice is pixel perfect for both desktop and mobile according to design
- [ ] I conducted basic QA to assure all features are working
- [ ] I tested responsive for mobile and tablet resolutions

## Backend checklist:

- [ ] I tested admin by manually adding content from zero
- [ ] I created easy to use admin experience which is self-explanatory
- [ ] I added description to admin fields in hard-to-understand areas
- [ ] I followed guidelines for naming `Typescript` variables
- [ ] I conducted basic QA to assure all features are working

2023-12-10 15:52 UTC, Mikazian commented on .eslintrc.cjs
> +<<<<<<< HEAD
Problème ici surement à cause de la résolution de conflits, à corriger

2023-12-10 15:52 UTC, Mikazian commented on packages/backend/api/src/cities/get-cities.ts
> +city.get('/cities', async (_req, res) => {
J'ai fais un PR pour le crud city qu'on utilisera. On garde celui ci pour l'instant mais on fera un fix pour utiliser qui viendra

2023-12-10 15:52 UTC, Mikazian commented on packages/backend/api/src/register.ts
> +    // city_id,
attention, code commenté

2023-12-10 15:52 UTC, Mikazian commented on packages/backend/api/src/register.ts
> +register.post('/', async (req, res) => {
`register.post('/users, async (req, res)...`

2023-12-10 15:52 UTC, Mikazian commented on packages/backend/api/src/register.ts
> +  const { name, role, birthdate, gender, biography, account_github, email, password } = req.body; //city_id,
city_id commenté

2023-12-10 15:52 UTC, Mikazian commented on packages/backend/api/src/register.ts
> +const register = express.Router();
changer en
`const registerProfileRouter = express.Router()`
pour ne pas confondre avec la partie register de Melvin
et à changer partout

2023-12-10 15:52 UTC, Mikazian commented on packages/backend/api/src/cities/get-cities.ts
> +const city = express.Router();
`const cityRouter = express.Router()`

2023-12-10 15:52 UTC, Mikazian commented on packages/backend/api/src/router.ts
> +router.use('/register', register);
Si les modifs au dessus ont été faites, mettre à jour ce router

2023-12-10 15:52 UTC, Mikazian commented on packages/backend/api/src/router.ts
> +router.use('/', city);
Pareil ici

2023-12-10 15:52 UTC, Mikazian commented on packages/frontend/web/src/components/Button.tsx
>    readonly isOutline: boolean;
Si tu as ajouté des props supplémentaires, ajouter le typage dans l'interface ButtonProps

2023-12-10 15:52 UTC, Mikazian commented on packages/frontend/web/src/components/Button.tsx
> +      onClick={onClick}
Vérifier si ça casse pas les autres buttons dans les autres pages avec le onClick

2023-12-10 15:52 UTC, Mikazian commented on packages/frontend/web/src/components/Button.tsx
> +      } border-primary ${color} font-base w-full max-w-[500px] shrink-0 rounded-lg border px-2 py-3 text-xl`}
La couleur du texte doit toujours être blanc, peut importe le thème, à vérifier ici

2023-12-10 15:52 UTC, Mikazian commented on packages/frontend/web/src/components/Forms/FormBirthDate.tsx
> +  const { register } = useFormContext();
Dans FormBio tu as typé ton useFormContext() avec un type DefaultValue, pourquoi pas ici ?

2023-12-10 15:52 UTC, Mikazian commented on packages/frontend/web/src/components/Forms/FormCity.tsx
> +  const { register } = useFormContext();
Pareil ton context n'a pas été typé comme FormBio.
Ta un type City dejà définit
essaie : `type DefaultValue = City[];`
pour typer ton context

2023-12-10 15:52 UTC, Mikazian commented on packages/frontend/web/src/components/Forms/FormCity.tsx
> +      const response = await fetch(`${import.meta.env.VITE_API_URL}/cities`, {
pour faire plus propre, créer une `const API_URL = import.meta.env.VITE_API_URL` en dehors du composant et l'appeler dans ton fetch

2023-12-10 15:52 UTC, Mikazian commented on packages/frontend/web/src/components/Forms/FormName.tsx
> +  const { errors } = formState;
Attention, on utilisera zod pour afficher les messages d'erreurs

2023-12-10 15:52 UTC, Mikazian commented on packages/frontend/web/src/components/Forms/FormName.tsx
> +        <p>{errors.name?.message}</p>
Retirer cette ligne car on utilisera zod

2023-12-10 15:52 UTC, Mikazian commented on packages/frontend/web/src/components/Forms/FormTest.tsx
> +export default function FormTest() {
Attention ta push un formulaire qui ne doit pas être dans registration profile

2023-12-10 15:52 UTC, Mikazian commented on packages/frontend/web/src/pages/FormProfile.tsx
> +  console.log(isDirty, isValid);
Attention ta laissé un console.log

2023-12-10 15:52 UTC, Mikazian commented on packages/frontend/web/src/pages/FormProfile.tsx
> +  console.log(page);
Pareil ici

2023-12-10 15:52 UTC, Mikazian commented on packages/frontend/web/src/pages/FormProfile.tsx
> +    console.log('Valeur stocké:', getValues());
Pareil ici

2023-12-10 15:52 UTC, Mikazian commented on packages/frontend/web/src/pages/FormProfile.tsx
> +      <NavBar />
Enlever le composant NavBar, tu dois avoir que ton formulaire

2023-12-10 15:52 UTC, Mikazian commented on packages/frontend/web/src/components/Forms/FormIAm.tsx
> +type DefaultValues = {
tu as créé un type Gender dans database.ts du dossier type, tu importer ce type et l'attribué au DefaultValues
`import { Gender } from '@app/types`
`DefaultValues = Gender`

2023-12-10 16:00 UTC, Mikazian commented
Je t'ai ajouté des correctifs à faire, et pour optimiser tes formulaires afin d'éviter la répétition de code, tu peux créer un composant FormBase.ts qui sera un template pour tous tes fomulaires et qui contiendra des props children et title par exemple :
`export default function Fombase(children, title) => {
return (
 <div className='font-base w-full flex-col items-center pt-40'>
      <h1 className='text-primary font-title mb-4 justify-start text-2xl lg:text-3xl'>
        {title}
      </h1>
      <div className='bg-light text-secondary mb-2 rounded-md px-7 pb-12 pt-5 text-sm shadow-md lg:text-base'>
      {children}
      </div>
</div>
)
}`

2023-12-10 16:10 UTC, Mikazian commented on packages/backend/api/src/router.ts
>  router.get('/', async (_request, response) => {
Tu peux retirer les routes par défaut, on les utilisera jamais

2023-12-10 16:10 UTC, Mikazian commented
Je t'ai ajouté des correctifs à faire, et pour optimiser tes formulaires afin d'éviter la répétition de code, tu peux créer un composant FormContainer.tsx qui sera un template pour tous tes formulaires et qui contiendra des props children et title par exemple
Petit plus, ajouter des commentaires sur des parties de code complexe

2023-12-22 09:17 UTC, Mikazian commented on packages/frontend/web/src/components/forms/FormBirthDate.tsx
> +          validate: (value) => {
tester avec refine de zod

2023-12-22 09:17 UTC, Mikazian commented on packages/frontend/web/src/components/forms/FormCity.tsx
> +        const abortController = new AbortController();
const controller

2023-12-22 09:17 UTC, Mikazian commented on packages/frontend/web/src/components/forms/FormCity.tsx
> +                signal: abortController.signal,
controller.signal

2023-12-22 09:17 UTC, Mikazian commented on packages/frontend/web/src/components/forms/FormCity.tsx
> +          abortController.abort();
controller.abort()

2023-12-22 09:17 UTC, Mikazian commented on packages/frontend/web/src/components/forms/FormHobby.tsx
> +interface Hobby {
Créer un schéma zod et infer le schéma pour ton typage

2023-12-22 09:17 UTC, Mikazian commented on packages/frontend/web/src/components/forms/FormHobby.tsx
> +interface Category {
Pareil ici

2023-12-22 09:17 UTC, Mikazian commented on packages/frontend/web/src/components/forms/FormHobby.tsx
> +interface FormValues extends Category {}
Cette ligne sert à rien

2023-12-22 09:17 UTC, Mikazian commented on packages/frontend/web/src/components/forms/FormHobby.tsx
> +  const { register, watch } = useFormContext<FormValues>();
Enlever FormValue et mettre ton typage pour la Category

2023-12-22 09:17 UTC, Mikazian commented on packages/frontend/web/src/components/forms/FormHobby.tsx
> +    const abortController = new AbortController();
controller

2023-12-22 09:17 UTC, Mikazian commented on packages/frontend/web/src/components/forms/FormHobby.tsx
> +      abortController.abort();
controller

2023-12-22 09:17 UTC, Mikazian commented on packages/frontend/web/src/components/forms/FormHobby.tsx
> +                    {...register('hobbies', { required: true })}
enlever le required, zod le fait deja

2023-12-22 09:17 UTC, Mikazian commented on packages/frontend/web/src/components/forms/FormName.tsx
> +        {...register('name', {
Avec zod tu peux gérer le patern aussi

2023-12-22 09:17 UTC, Mikazian commented on packages/frontend/web/src/components/forms/LanguageAndTechnologyContainer.tsx
> +  const { register } = useFormContext<DefaultValues>();
Il est pas typé avec zod ? Il manque le formState pour les erreurs

2023-12-22 10:15 UTC, ElBarto444 commented on packages/frontend/web/src/components/forms/FormTest.tsx
> +              message: 'Pas top l email non ? ',
Tu le changeras ça ?

2023-12-22 10:15 UTC, ElBarto444 commented on packages/frontend/web/src/components/forms/LanguageAndTechnologyContainer.tsx
logs à retirer ici

2023-12-22 16:02 UTC, greegouze commented on packages/frontend/web/src/components/forms/FormTest.tsx
> +              message: 'Pas top l email non ? ',
Yep ^^

2024-01-11 16:24 UTC, Mikazian commented on packages/frontend/web/src/components/forms/LanguageAndTechnologyContainer.tsx
> +  }, [apiUrl, fieldName]);
possibilité de faire un hook custom

2024-01-11 16:24 UTC, Mikazian commented on packages/frontend/web/src/components/forms/FormLanguage.tsx
> +    fieldName: 'languages' as FieldName,
as FieldName est nécessaire ? FieldName est = à languages

2024-01-11 16:24 UTC, Mikazian commented on packages/frontend/web/src/components/forms/FormTechnology.tsx
> +    fieldName: 'technologies' as FieldName,
Pareil ici

2024-01-11 16:24 UTC, Mikazian commented on packages/frontend/web/tailwind.config.js
> +        primary: '#eb0573',
var(--primary) ça marche pas ?

2024-01-11 19:40 UTC, Mikazian submitted a review, later dismissed

2024-01-12 09:04 UTC, greegouze commented on packages/frontend/web/src/components/forms/FormLanguage.tsx
> +    fieldName: 'languages' as FieldName,
Yep vue que j'envoie fieldName en props

2024-01-14 15:16 UTC, Mikazian commented on packages/frontend/web/src/components/forms/FormBio.tsx
> +          <p className='error-message'>{errors.biography.message}</p>
Tu as créé une classe custom pour ce message d'erreur ? Tu utilises pas les mêmes classes que tes autres composant

2024-01-14 15:16 UTC, Mikazian commented on packages/frontend/web/src/components/forms/FormHobby.tsx
> +        <p className='error-message'>{errors.hobbies.message}</p>
Pareil ici les classe de ton message d'erreur

2024-01-14 15:16 UTC, Mikazian commented on packages/frontend/web/src/components/forms/FormName.tsx
> +        </label>
Deux label ? C'est pas possible de mettre un span dans le label avec une classe ?

2024-01-14 15:16 UTC, Mikazian commented on packages/frontend/web/src/components/forms/FormIAm.tsx
J'aurai renommé ce fichier en FormGender, c'est plus parlant que FormIAm

2024-01-14 15:52 UTC, greegouze commented on packages/frontend/web/src/components/Button.tsx
> +  useTheme();
Pour ajouter le onClick de retour en arrière, si je le retire celui si ne fonctionne pas. Et si tu parle de useTheme, c'est pour la ternaire afin de vérifier si le theme est en dark ou light  " className={`${
        isOutline
          ? `bg-transparent ${theme === 'dark' ? 'text-white' : 'text-primary'}`
          : 'bg-primary text-white'"

2024-01-14 15:53 UTC, greegouze commented on packages/frontend/web/src/components/forms/FormBio.tsx
> +          <p className='error-message'>{errors.biography.message}</p>
eux mince un oublie, je le retire !

2024-01-14 15:57 UTC, greegouze commented on packages/frontend/web/src/components/forms/FormTest.tsx
Comme je l'ai indiqué en en haut du fichier // While waiting for the PR register . Vue que le password et l'email sont require et que nous n'avons pas encore la partie de Melvyn obligé de mettre ce formulaire. Il sera à retirer une fois que la pr de melvin sera passé et que cette pr soit merge sur dev. (Si Sylvain veux tester que l'insertion en bdd fonctionne pas le choix non plus)

2024-01-15 10:54 UTC, Mikazian commented on packages/frontend/web/src/components/Button.tsx
> +  useTheme();
ton useTheme() tout seul il sert à rien puisque en bas tu fais : `const { theme } = useTheme();`

2024-01-15 10:54 UTC, Mikazian commented on packages/frontend/web/src/router.tsx
> +    path: '/register/profile',
pour que ça soit cohérent avec la partie de melvin :
registration,
registration/success,
registration/validation

et toi :

registration/profile

vu qu'on est toujours dans la registration

2024-01-15 11:29 UTC, Mikazian submitted a review, later dismissed

2024-01-15 15:23 UTC, ElBarto444 submitted a review, later dismissed

2024-01-22 09:42 UTC, YDrogen requested changes

2024-01-22 09:42 UTC, YDrogen commented on packages/frontend/web/src/pages/FormProfile.tsx
> +import React from 'react';
pas obligé

2024-01-22 09:42 UTC, YDrogen commented on packages/frontend/web/src/pages/FormProfile.tsx
> +import { useState } from 'react';
Tu peux importer `Fragment` d'ici

2024-01-22 09:42 UTC, YDrogen commented on packages/frontend/web/src/components/forms/FormTest.tsx
> +              message: 'Invalid Email. ',
espace
```suggestion
              message: 'Invalid Email.',
```

2024-01-22 09:42 UTC, YDrogen commented on packages/frontend/web/src/components/forms/FormTechnology.tsx
> +  };
À sortir hors du component

2024-01-22 09:42 UTC, YDrogen commented on packages/frontend/web/src/components/forms/FormLanguage.tsx
> +  };
idem

2024-01-22 09:42 UTC, YDrogen commented on packages/frontend/web/src/components/forms/FormContainer.tsx
> +interface Container extends React.HTMLAttributes<HTMLDivElement> {}
`NomDuComponentProps` -> `FormContainerProps`

2024-01-22 09:42 UTC, YDrogen commented on packages/frontend/web/src/components/forms/FormGender.tsx
> +  ];
Peut être sorti hors du component

2024-01-22 09:42 UTC, YDrogen commented on packages/backend/api/src/hobby/hobby-crud.ts
> +            .limit(31),
Pourquoi `.limit(31)` ?

2024-01-22 09:42 UTC, YDrogen commented on .eslintrc.cjs
> +        'react-refresh/only-export-components': 'off',
why?

2024-01-22 11:17 UTC, Mikazian approved these changes

2024-01-22 11:17 UTC, Mikazian commented
J'ai vérifié, les changements ont été apportés

2024-01-22 16:02 UTC, Mikazian submitted a review, later dismissed

2024-01-29 16:19 UTC, YDrogen requested changes
Impossible de tester, quand je m'inscris, ça me demande de valider mon compte et c'est tout, après j'arrive direct sur la page pour swiper

2024-01-30 11:03 UTC, Mikazian commented on packages/frontend/web/src/components/forms/FormTest.tsx
à retirer

2024-01-30 20:01 UTC, Mikazian approved these changes

2024-01-31 11:24 UTC, YDrogen requested changes
![image](https://github.com/WildCodeSchool/2023-09-orleans-cda-projet2-groupe-c/assets/13053644/2eccf762-fb5b-4c81-b16a-81455f9fba42)
Je ne suis pas redirigé quand je me login dans ce cas (sans valider)

Si je ne remplis pas mon profil, je ne peux plus le faire plus tard (je suis redirigé sur la home à la connexion), ça me redirige vers l'inscription si j'essaie d'y retourner
j'sais pas si c'est normal

2024-01-31 11:24 UTC, YDrogen commented on packages/frontend/web/src/hooks/use-selected-items.ts
Ceci sert à rien
Tu peux faire la même chose avec le form context
Idem pour le local storage, pas utile

2024-01-31 11:24 UTC, YDrogen commented on packages/frontend/web/src/pages/FormProfile.tsx
> +          array.map((item: string) => JSON.parse(item) as SelectedItemBody);
Peut être sorti hors du component

2024-01-31 11:24 UTC, YDrogen commented on packages/frontend/web/src/pages/FormProfile.tsx
> +    if (page < 9) {
Y'a pas un truc à faire avec PAGES.length ?

2024-01-31 11:24 UTC, YDrogen commented on packages/frontend/web/src/components/forms/FormBirthDate.tsx
Ça manque d'un petit message de félicitations pour les utilisateurs ayant vu Jesus grandir (suivi d'un questionnaire, on pourrait avoir des questions à leur poser)

2024-01-31 14:41 UTC, Mikazian commented on packages/frontend/web/src/pages/FormProfile.tsx
> +          array.map((item: string) => JSON.parse(item) as SelectedItemBody);
fait

2024-01-31 14:43 UTC, Mikazian commented on packages/frontend/web/src/pages/FormProfile.tsx
> +    if (page < 9) {
corrigé

2024-01-31 14:51 UTC, Mikazian commented on packages/frontend/web/src/components/forms/FormBirthDate.tsx
j'ai ajouté un refine supplémentaire dans le schéma zod pour que les plus de 100 ans de puisse pas s'inscrire

2024-02-07 21:26 UTC, Mikazian commented on packages/frontend/web/src/pages/FormProfile.tsx
> +          array.map((item: string) => JSON.parse(item) as SelectedItemBody);
retiré, j'utilise maintenant useController qui me permet d'avoir { id, order } directement

2024-02-07 21:26 UTC, Mikazian commented on packages/frontend/web/src/hooks/use-selected-items.ts
le custom hook a été retiré. J'ai déporté le code directement dans le composant.

2024-02-12 21:45 UTC, Mikazian commented
Gros changement apporté sur cette PR :
- modification de la route verify, ajout d'un boolean isActived pour savoir si un compte est activé. Utilisé pour les redirections,
- retouche du AuthContext qui vérifie bien qui la data est ok avant de set les states,
- ajout de la progress bar qui se remplit à chaque formulaire soumis, 
- retouche de la registration email, password, code d'activation et ajustement du CSS,
- retouche du formulaire activation code en 6 inputs,
- retouche de la registration profile et ajustement du CSS,
- retouche du formulaire birthdate en 3 inputs pour year, month et day
- gros changement pour la partie Technology, Language, Hobby, utilisation du useController de useForm afin d'envoyer un objet { id, order } en data
- ajout des redirections si un utilisateur n'a pas remplit le code d'activation ou son profil utilisateur,
- modification des schémas zod

2024-02-16 11:21 UTC, Mikazian approved these changes

2024-02-19 09:16 UTC, Mikazian approved these changes

2024-02-20 19:50 UTC, Mikazian commented on packages/backend/api/src/register.ts
> +import type { Request } from '@app/shared';
corrigé

2024-02-20 19:58 UTC, Mikazian commented on packages/frontend/web/src/components/Button.tsx
> +          ? `bg-transparent ${theme === 'dark' ? 'text-white' : 'text-primary'}`
corrigé

2024-02-20 20:03 UTC, Mikazian commented on packages/frontend/web/src/pages/Home.tsx
> +      userProfile.hobbies.length === 0)
Les deux conditions ne sont pas les mêmes : 
J'ai stocké la première condition dans hasCompleteRegistration qui check si le code d'activation est rempli et si les champs du profile n'est pas rempli === 0,
La deuxième condition hasCompleteProfile check si le code est activé et si les champs du profile > 0

2024-02-20 20:06 UTC, Mikazian commented on packages/frontend/web/src/pages/FormProfile.tsx
> +  { currentPage: 9, component: <FormEnd /> },
c'est Greg qui les a appelés comme ça, je corrige

2024-02-20 20:07 UTC, Mikazian commented on packages/frontend/web/src/pages/Home.tsx
> +        credentials: 'include', // Send cookies
retiré

2024-02-20 20:12 UTC, Mikazian commented on packages/frontend/web/src/components/forms/LanguageAndTechnologyContainer.tsx
> +  // eslint-disable-next-line @typescript-eslint/no-unnecessary-condition, @typescript-eslint/strict-boolean-expressions
j'avais un message warning qui m'énervé

2024-02-20 20:12 UTC, Mikazian commented on packages/frontend/web/src/components/forms/FormHobby.tsx
> +  // eslint-disable-next-line @typescript-eslint/no-unnecessary-condition, @typescript-eslint/strict-boolean-expressions
pareil ici

2024-02-20 20:13 UTC, Mikazian commented on packages/frontend/web/src/components/forms/LanguageAndTechnologyContainer.tsx
> +  // eslint-disable-next-line @typescript-eslint/no-unnecessary-condition, @typescript-eslint/strict-boolean-expressions
Le code provient de la doc officiel de useForm, j'ai repris l'exemple donnée dans le useController pour les checkbox

2024-02-20 20:25 UTC, Mikazian commented on packages/shared/src/auth.ts
> +  code_6: z.string().trim().length(1),
J'ai pas trop compris du coup j'ai créé une fonction qui retourne ce schéma pour l'appliqué au 6 inputs

2024-02-20 20:29 UTC, Mikazian commented on packages/frontend/web/src/contexts/AuthContext.tsx
> +  isActived: boolean;
j'ai corrigé le nom et mis à jour partout il ou était utilisé

2024-02-20 20:50 UTC, Mikazian commented on packages/frontend/web/src/components/forms/LanguageAndTechnologyContainer.tsx
> +  // eslint-disable-next-line @typescript-eslint/no-unnecessary-condition, @typescript-eslint/strict-boolean-expressions
Après plusieurs essaies pour enlevé ce warning, j'ai fais une ternaire dans le useState

2024-02-20 20:55 UTC, Mikazian approved these changes

2024-02-21 08:54 UTC, YDrogen commented on packages/frontend/web/src/pages/Home.tsx
> +      userProfile.hobbies.length === 0)
La partie où tu vérifie les champs de `userProfile` peut être sortie dans une const `hasCompleteProfile`
`const hasCompleteProfile = Boolean(userProfile.name) && Boolean(userProfile.birthdate) // ...`
Ensuite tu inverse si besoin... `!hasCompleteProfile`

2024-02-21 10:40 UTC, Mikazian commented on packages/shared/src/auth.ts
> +  code_6: z.string().trim().length(1),
corrigé

2024-02-21 10:51 UTC, Mikazian commented on packages/frontend/web/src/components/forms/LanguageAndTechnologyContainer.tsx
> +  }, [apiUrl, items, value]);
corrigé

2024-02-21 10:56 UTC, Mikazian commented on packages/frontend/web/src/pages/Home.tsx
> +      userProfile.hobbies.length === 0)
corrigé

2024-02-21 10:59 UTC, Mikazian approved these changes

2024-02-21 11:26 UTC, YDrogen approved these changes

2024-02-21 11:27 UTC, merged