Feature/home registration
WildCodeSchool/2023-09-orleans-cda-projet2-groupe-c pull request #96
Opened 2023-12-14 15:41 UTC by ElBarto444

## Description

Please include a summary of the change or which issue is fixed.

## Type of change

- [ ] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Area of change

- [ ] Frontend
- [ ] Backend
- [ ] Other: .....

## General checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I ran `bun run format`/`bun run lint` before commit
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation where needed
- [ ] My changes generate no new warnings
- [ ] I have checked my code and corrected any misspellings
- [ ] I have updated `develop` and merged to my branch before submitting pull request
- [ ] My pull request generate no conflicts with `develop` branch
- [ ] I requested code review from other team members

## Frontend checklist:

- [ ] I followed guidelines for `HTML`/`JSX`/`Typescript`
- [ ] My `Javascript` generate no new console errors
- [ ] I tested my code cross browsers
- [ ] My slice is pixel perfect for both desktop and mobile according to design
- [ ] I conducted basic QA to assure all features are working
- [ ] I tested responsive for mobile and tablet resolutions

## Backend checklist:

- [ ] I tested admin by manually adding content from zero
- [ ] I created easy to use admin experience which is self-explanatory
- [ ] I added description to admin fields in hard-to-understand areas
- [ ] I followed guidelines for naming `Typescript` variables
- [ ] I conducted basic QA to assure all features are working

2023-12-14 18:45 UTC, Mikazian commented on packages/backend/api/src/auth.ts
> +  // const userId = 47;
Code commenté à enlever

2023-12-14 18:45 UTC, Mikazian commented on packages/backend/api/src/utils/error-handler.ts
Il sert à quoi ce fichier ? Les messages d'erreurs ? Si c'est le cas, je pense ce fichier est inutile, il utilise zod pour gérer les messages d'erreurs et les exceptions

2023-12-14 18:45 UTC, Mikazian commented on packages/backend/api/src/auth.ts
Ajouter des commentaires ça serait cool pour la relecture et pour la certif :)

2023-12-14 18:45 UTC, Mikazian commented on packages/backend/api/src/utils/token-generator.ts
Des commentaires, je comprends rien à ce code D:

2023-12-14 18:45 UTC, Mikazian commented on packages/frontend/web/index.html
> +  <body style="background-color: #f4efef">
C'est quoi ça ? Pourquoi avoir mis du style dans ce fichier ?

2023-12-14 18:45 UTC, Mikazian commented on packages/frontend/web/public/check.svg
check.svg à supprimer. Je crois que tu as créé un composant Check.tsx
c'est la même chose non ?

2023-12-14 18:45 UTC, Mikazian commented on packages/frontend/web/src/components/auth/Registration.tsx
Ajouter des commentaires pour la relecture, merci

2023-12-14 18:45 UTC, Mikazian commented on packages/frontend/web/src/components/auth/Registration.tsx
Je te met le lien que Sylvain m'a envoyé pour le hook useForm + Zod : [https://github.com/react-hook-form/resolvers#zod](url)

Tu as un exemple dans ce lien, très facile à implémenter, tu devras modifier ton code.
Je t'ai mis des commentaires sur les parties qu'il faudra modifier.

Il faudra installer d'abord le package @hookform/resolvers dans le dossier "shared", chez toi c'est le dossier "type" : 

et importer : 

`import { zodResolver } from '@hookform/resolvers/zod';`

2023-12-14 18:45 UTC, Mikazian commented on packages/frontend/web/src/components/auth/Registration.tsx
> +  const { isValid } = formState;
ajouter : `const { isValid, errors } = formState;`

2023-12-14 18:45 UTC, Mikazian commented on packages/frontend/web/src/components/auth/Registration.tsx
> +  const { register, handleSubmit, formState } = useForm<RegisterBody>({
modifier : `  const { register, handleSubmit, formState } = useForm<RegisterBody>({
    resolver: zodResolver(schema),
  });`

Important : installer la dépendance @hookform/resolvers que j'avais cité plus haut pour utiliser zodResolver qui va servir à utiliser zod comme schéma de validation pour le formulaire

2023-12-14 18:45 UTC, Mikazian commented on packages/frontend/web/src/components/auth/Registration.tsx
> +    criteriaMode: 'all',
à retirer

2023-12-14 18:45 UTC, Mikazian commented on packages/frontend/web/src/components/auth/Registration.tsx
> +  const [formErrors, setFormErrors] = useState<{
Tu peux supprimer cette variable, on va gérer les messages d'erreurs avec l'objet errors du formState

2023-12-14 18:45 UTC, Mikazian commented on packages/frontend/web/src/components/auth/Registration.tsx
> +    const result = authSchema.safeParse(data);
à supprimer, on va gérer les messages d'erreurs avec l'objet errors du formState

2023-12-14 18:45 UTC, Mikazian commented on packages/frontend/web/src/components/auth/Registration.tsx
> +    if (result.success) {
supprimer tout le block if/else

2023-12-14 18:45 UTC, Mikazian commented on packages/frontend/web/src/components/auth/Registration.tsx
> +      throw new Error(`Failed to register. : ${String(error)}`);
Enlever le " . " après Failed to register xD

2023-12-14 18:45 UTC, Mikazian commented on packages/frontend/web/src/components/auth/Registration.tsx
> +            <p className='text-next'>{formErrors.email}</p>
ça sera plus formErrors.email mais : 
`      {errors.email?.message && <p>{errors.email?.message}</p>}
`

Comme sur la doc que je t'ai envoyé mais attention tu auras un message warning, j'ai pas encore trouvé la solution pour la corriger

2023-12-14 18:45 UTC, Mikazian commented on packages/frontend/web/src/components/auth/Registration.tsx
> +            <p className='text-next'>{formErrors.password}</p>
Pareil ici, on utilisera l'objet errors du formState

2023-12-14 18:45 UTC, Mikazian commented on packages/frontend/web/src/components/auth/Registration.tsx
> +            <button
Est ce que tu as pull develop ?
Tu pourras utiliser le composant `<Button />`

2023-12-14 18:45 UTC, Mikazian commented on packages/frontend/web/src/components/auth/Success.tsx
> +          <button
Pareil ici, utiliser le composant `<Button />`

2023-12-14 18:45 UTC, Mikazian commented on packages/frontend/web/src/components/auth/ValidationToken.tsx
Tu vas pareil que le fichier Registration.tsx et ajouter des commentaires stp

2023-12-14 18:45 UTC, Mikazian commented on packages/frontend/web/src/components/auth/ValidationToken.tsx
> +              // onChange={(event) => {setCode(event.target.value)}}
code commenté à retirer

2023-12-14 18:45 UTC, Mikazian commented on packages/frontend/web/src/components/auth/ValidationToken.tsx
> +              <button
composant `<Button />`

2023-12-14 18:45 UTC, Mikazian commented on packages/frontend/web/src/router.tsx
Tes routes ne sont pas des childrens de Home, tu devras créer une route principale '/registration' avec un composant Registration.tsx qui sera dans le dossier ./packages/frontend/web/src/pages et va retourner un `<Outlet />`
Tu devras renommer ton fichier ./packages/frontend/web/src/components/auth/Registration.tsx en RegistrationForm.tsx ça sera plus simple pour ne pas les confondre.
Ensuite tu auras des childrens de ta route '/registration' : 
- le premier sera '/' et qui aura un element `<RegistrationForm />`,
- le second sera '/success' et qui aura un element `<Success />`,
- et le dernier '/validation' et qui aura un element `<ValidationToken />`

2023-12-14 18:45 UTC, Mikazian commented on packages/frontend/web/src/utils/token-generator/token-generator.ts
Fichier à supprimer, il est utilisé seulement dans le backend

2023-12-14 19:55 UTC, Mikazian commented on packages/frontend/web/src/components/auth/Registration.tsx
> +      const validate = authSchema.parse({
Tu peux supprimer les constantes qui sont parsé avec zod, si tu as mis resolver de zod plus haut y'a plus besoin de parser

2023-12-15 08:46 UTC, greegouze commented on packages/backend/api/src/utils/token-generator.ts
> +}
essaie de commenter toute cette partie du code. Il est assez lourd histoire que l'on comprenne mieux

2023-12-15 08:52 UTC, greegouze commented on packages/types/src/database.ts
> +  role?: Role;
Pas besoin de role? il est par défaut en user

2023-12-15 09:09 UTC, ElBarto444 commented on packages/frontend/web/src/components/auth/Registration.tsx
Le lien est DCD

2023-12-16 17:11 UTC, Mikazian commented on packages/frontend/web/src/components/auth/RegistrationForm.tsx
> +  const { register, handleSubmit, formState } = useForm<RegisterBody>({
Le typage sera plus RegisterBody mais : 

```ruby
  const { register, handleSubmit, formState } = useForm<AuthWithRoleAndActivationCode>({
    resolver: zodResolver(authSchema),
  });
```

qui comprend le typage d'email, password, activation_code et email_verified_at

2023-12-16 17:11 UTC, Mikazian commented on packages/frontend/web/src/components/auth/RegistrationForm.tsx
> +            <button
Utiliser le composant `<Button />`

2023-12-18 12:33 UTC, Mikazian commented
Les corrections ont été faites. Tu as un composant`<Button />` qui est prêt à être utiliser dans le dossier src/components. Il faut les placer dans tes formulaires. Et ta PR est en conflits

2023-12-18 14:50 UTC, Mikazian commented on packages/backend/api/src/router.ts
> +// prettier-ignore
Retirer cette ligne
si ta PR passe pas c'est parce qu'il faut faire : `bun run lint && bun run format`

2023-12-18 21:11 UTC, Mikazian commented on packages/backend/api/src/auth.ts
> +    return res.json({ ok: true, isLoggedIn: true });
Ici, tu peux enlever isLoggedIn, l'utilisateur n'est pas encore connecté, ce booléan sert uniquement partie Login

2023-12-18 21:11 UTC, Mikazian commented on packages/backend/api/src/auth.ts
> +    return res.json({ isLoggedIn: false, error });
Pareil ici, tu peux retourner juste l'erreur

2023-12-18 21:11 UTC, Mikazian commented on packages/backend/api/src/auth.ts
> +  const userId = req.signedCookies.userId;
J'ai check ton code, userId est de type any, juste ajouter : number

2023-12-18 21:11 UTC, Mikazian commented on packages/backend/api/src/auth.ts
> +  const { activation_code } = req.body;
Pour résoudre le problème de prettier : 
```ruby
    const { activation_code: activationCode }: ActivationCode = req.body;
```

2023-12-18 21:11 UTC, Mikazian commented on packages/backend/api/src/auth.ts
> +  const activationCode = await db
Changer le nom car il a le même nom que la variable plus haut : 
```ruby
  const getCode = await db
      .selectFrom('user')
      .select('activation_code')
      .where('id', '=', userId)
      .execute();
```

2023-12-18 21:11 UTC, Mikazian commented on packages/backend/api/src/auth.ts
> +  if (activation_code === activationCode[0].activation_code) {
Modifier les variables de la conditions : 
```ruby
if (activationCode === getCode[0].activation_code) {
      const code: ActivationToken = {
        activation_code: '',
        activate_at: new Date(),
      };
```

2023-12-18 21:11 UTC, Mikazian commented on packages/frontend/web/src/components/auth/RegistrationForm.tsx
> +import type { AuthWithRoleAndActivationCode } from '@app/types';
Changer l'importation : 
```ruby
import type { RegisterBody } from '@app/types';
```

2023-12-18 21:11 UTC, Mikazian commented on packages/frontend/web/src/components/auth/RegistrationForm.tsx
> +  const onSubmit: SubmitHandler<AuthWithRoleAndActivationCode> = async (
Changer le typage du onSubmit : 
```ruby
  const onSubmit: SubmitHandler<RegisterBody> = async (data) => {
```

2023-12-18 21:11 UTC, Mikazian commented on packages/frontend/web/src/components/auth/ValidationToken.tsx
> +import { type FieldValues, type SubmitHandler, useForm } from 'react-hook-form';
enlever le FieldValues

2023-12-18 21:11 UTC, Mikazian commented on packages/frontend/web/src/components/auth/ValidationToken.tsx
> +const onSubmit: SubmitHandler<FieldValues> = async (data) => {
remplacer le FieldValues par : 
```ruby 
const onSubmit: SubmitHandler<ActivationCode> = async (data) => {
```

2023-12-18 21:11 UTC, Mikazian commented on packages/types/src/auth.ts
Enlève tout le code de ce fichier et met ça : 
```ruby 
import { z } from 'zod';

export const userSchema = z
  .object({
    name: z
      .string({
        required_error: 'ⓘ Name is required.',
        invalid_type_error: 'ⓘ Name must be a string.',
      })
      .trim()
      .min(3, { message: 'ⓘ Name must be more than 3 characters.' })
      .max(255, { message: 'ⓘ Name must be less than 255 characters.' }),
    birthdate: z.date({ required_error: 'ⓘ Birthdate is required.' }).refine(
      (date) => {
        // Calculate user age for registration, user must be >= 18 years old
        const age = new Date().getFullYear() - date.getFullYear();

        return age >= 18;
      },
      { message: 'ⓘ You must be 18 years old to register.' },
    ),
    gender: z.enum(['male', 'female', 'non-binary']),
    biography: z.optional(
      z.string().trim().max(1000, {
        message: 'ⓘ Biography must be less than 1000 characters.',
      }),
    ),
    account_github: z.optional(
      z
        .string()
        .trim()
        .url({ message: 'ⓘ Your account Github must be a url valid.' })
        .max(255, {
          message: 'ⓘ Your account Github must be less than 255 characters.',
        }),
    ),
    role: z.enum(['user', 'admin']),
    email: z
      .string({
        required_error: 'ⓘ Email is required.',
        invalid_type_error: 'ⓘ Email must be a string.',
      })
      .trim()
      .email({ message: 'ⓘ Email must be a valid email.' })
      .max(255, { message: 'ⓘ Email must be less than 255 characters.' }),
    password: z
      .string({
        required_error: 'ⓘ Password is required.',
        invalid_type_error: 'ⓘ Password must be a string.',
      })
      .trim()
      .min(8, { message: 'ⓘ Password must be more than 8 characters.' })
      .max(255, { message: 'ⓘ Password must be less than 255 characters.' }),
    email_verified_at: z.date({
      required_error: 'ⓘ Email verified at is required.',
    }),
    activation_code: z
      .string({
        required_error: 'ⓘ Activation code is required.',
        invalid_type_error: 'ⓘ Activation code must be a string.',
      })
      .trim()
      .max(6, {
        message: 'ⓘ Activation code must be less than 255 characters.',
      }),
    activate_at: z.date({ required_error: 'ⓘ Activate at is required.' }),
    city_id: z
      .number({
        required_error: 'ⓘ City id is required.',
        invalid_type_error: 'ⓘ City id must be a number.',
      })
      .positive({ message: 'ⓘ City id must be a positive number.' })
      .nullable(),
  })
  .strict()
  .strip();

export const authSchema = userSchema.pick({
  email: true,
  password: true,
});

export const registerWithActivationCodeSchema = userSchema.pick({
  email: true,
  password: true,
  role: true,
  activation_code: true,
  email_verified_at: true,
});

export const activationCodeSchema = userSchema.pick({ activation_code: true });

export const activationTokenSchema = userSchema.pick({
  activation_code: true,
  activate_at: true,
});

export type RegisterBody = z.infer<typeof authSchema>;

export type RegisterWithActivationCode = z.infer<
  typeof registerWithActivationCodeSchema
>;

export type ActivationCode = z.infer<typeof activationCodeSchema>;

export type ActivationToken = z.infer<typeof activationTokenSchema>;

```

2023-12-19 11:00 UTC, Mikazian submitted a review, later dismissed

2023-12-19 15:47 UTC, greegouze submitted a review, later dismissed

2023-12-20 12:25 UTC, Mikazian commented on packages/backend/api/src/router.ts
> +router.use('/auth', authRouter);
Retirer cette ligne, elle est deja en haut

2023-12-20 12:25 UTC, Mikazian commented on packages/backend/api/src/auth.ts
Tu as supprimé ma partie login, voici ta partie + la mienne : 
```ruby
import express from 'express';
import * as jose from 'jose';

import { db } from '@app/backend-shared';
import type {
  ActivationCode,
  ActivationToken,
  AuthBody,
  RegisterBody,
  RegisterWithActivationCode,
} from '@app/shared';

import { tokenGenerator } from '@/utils/token-generator';

const JWT_SECRET = process.env.JWT_SECRET;
const FRONTEND_URL = 'http://localhost';

// Throw an error if the JWT_SECRET environment variable is not defined
if (JWT_SECRET === undefined) {
  throw new Error('JWT_SECRET is not defined');
}

// Encode the JWT secret
const secret = new TextEncoder().encode(JWT_SECRET);

const authRouter = express.Router();

// Route to register a new user
authRouter.post('/registration', async (req, res) => {
  try {
    const activationCode = tokenGenerator(); // Generating random uppercased code with 6 characters and numbers

    // Getting email and password from request body, followed by password hashing
    const { email, password } = req.body as RegisterBody;

    const hashedPassword = await Bun.password.hash(password, {
      algorithm: 'bcrypt',
      cost: 10,
    });

    // Creating user object with the data from request body
    const user: RegisterWithActivationCode = {
      email,
      password: hashedPassword,
      role: 'user',
      activation_code: activationCode,
      email_verified_at: new Date(),
    };

    const result = await db.insertInto('user').values(user).execute();

    const userId = result[0].insertId;

    // Creating JWT token with Jose library
    const jwt = await new jose.SignJWT({ sub: email })
      .setProtectedHeader({ alg: 'HS256' })
      .setIssuedAt()
      .setIssuer(FRONTEND_URL)
      .setAudience(FRONTEND_URL)
      .setExpirationTime('2h')
      .sign(secret);

    // A cookie containing the JWT token
    res.cookie('token', jwt, {
      httpOnly: true,
      sameSite: true,
      secure: process.env.NODE_ENV === 'production',
      signed: true,
    });

    // A cookie containing the user ID
    res.cookie('userId', userId, {
      httpOnly: true,
      sameSite: true,
      secure: process.env.NODE_ENV === 'production',
      signed: true,
    });

    try {
      await jose.jwtVerify(jwt, secret, {
        issuer: FRONTEND_URL,
        audience: FRONTEND_URL,
      });
    } catch (error) {
      res.status(401).json({ message: 'Token is not valid', error });
    }

    return res.json({ ok: true });
  } catch (error) {
    return res.json({ error });
  }
});

// Route to validate the activation code
authRouter.post('/registration/validation', async (req, res) => {
  try {
    const userId: number = req.signedCookies.userId;
    const { activation_code: activationCode }: ActivationCode = req.body;

    const getCode = await db
      .selectFrom('user')
      .select('activation_code')
      .where('id', '=', userId)
      .execute();

    if (activationCode === getCode[0].activation_code) {
      const code: ActivationToken = {
        activation_code: '',
        activate_at: new Date(),
      };

      await db.updateTable('user').set(code).where('id', '=', userId).execute();
    }
    res.json({ ok: true });
  } catch (error) {
    throw new Error(`Error validating activation code: ${String(error)}`);
  }
});

// Route to get the user's activation code from the database
authRouter.get('/registration/users/code', async (req, res) => {
  const userId = req.signedCookies.userId;

  const code = await db
    .selectFrom('user')
    .select('activation_code')
    .where('id', '=', userId)
    .execute();

  return res.json(code);
});

// Route to check the JWT token in the cookie and verify if the user is logged in
authRouter.get('/verify', async (req, res) => {
  // Get the JWT from the cookie
  const jwt: string | undefined = req.signedCookies.token;

  // If the JWT is undefined, return an error
  if (jwt === undefined) {
    return res.json({
      ok: false,
      isLoggedIn: false,
    });
  }

  try {
    // Verify the JWT
    await jose.jwtVerify(jwt, secret, {
      issuer: FRONTEND_URL,
      audience: FRONTEND_URL,
    });

    return res.json({
      ok: true,
      isLoggedIn: true,
    });
  } catch (error) {
    // If the JWT is expired
    if (error instanceof jose.errors.JWTExpired) {
      return res.json({
        ok: false,
        isLoggedIn: false,
      });
    }

    return res.json({
      ok: false,
      isLoggedIn: false,
      error,
    });
  }
});

// Route to login a user
authRouter.post('/login', async (req, res) => {
  // Extract the email and password from the request body
  const { email, password } = req.body as AuthBody;

  try {
    // Get the user from the database
    const user = await db
      .selectFrom('user')
      .select(['user.password'])
      .where('user.email', '=', email)
      .executeTakeFirst();

    // If the user doesn't exist, return an error
    if (user === undefined) {
      return res.json({
        ok: false,
        email: 'User does not exist',
        isLoggedIn: false,
      });
    }

    // Verify the password
    const isCorrectPassword = await Bun.password.verify(
      password, // password provided by the user
      user.password, // password stored in the database
      'bcrypt', // hashing algorithm used
    );

    // If the password is incorrect, return an error
    if (!isCorrectPassword) {
      return res.json({
        ok: false,
        isLoggedIn: false,
      });
    }

    // Create a new JWT with the library jose
    const jwt = await new jose.SignJWT({
      sub: email,
    })
      .setProtectedHeader({
        alg: 'HS256',
      })
      .setIssuedAt()
      .setIssuer(FRONTEND_URL)
      .setAudience(FRONTEND_URL)
      .setExpirationTime('2h')
      .sign(secret);

    // Define the cookie token with the JWT
    res.cookie('token', jwt, {
      httpOnly: true, // The cookie is not accessible via JavaScript but only via HTTP(S)
      sameSite: true, // The cookie is not accessible via cross-site requests
      secure: process.env.NODE_ENV === 'production',
      signed: true,
    });

    return res.json({
      ok: true,
      isLoggedIn: isCorrectPassword,
    });
  } catch (error) {
    return res.json({
      ok: false,
      isLoggedIn: false,
      error,
    });
  }
});

export default authRouter;
```

2023-12-20 12:28 UTC, Mikazian commented
Tu dois avoir un composant HomeButtons dans le dossier components : 
ajouter ton chemin dans la balise `<Link>`

et dans le component `<Login />` dans 'create one now', ajouter ton chemin dans le `<Link />`

2023-12-20 15:10 UTC, greegouze approved these changes

2023-12-20 15:12 UTC, Mikazian submitted a review, later dismissed

2023-12-21 10:59 UTC, YDrogen requested changes
Attention, dans ton backend tu as `src/auth.ts` et `src/auth/auth.ts`; Les 2 contenant des routes, il faudrait les fusionner ou mieux organiser ça
Un des deux n'est jamais utilisé ?

2023-12-22 08:13 UTC, greegouze approved these changes

2023-12-22 08:25 UTC, Mikazian submitted a review, later dismissed

2023-12-22 08:25 UTC, Mikazian commented
Corrigé apportée ! J'ai testé le site sur ma machine ça fonctionne !

2024-01-04 10:15 UTC, YDrogen requested changes

2024-01-04 10:15 UTC, YDrogen commented on packages/backend/api/src/utils/token-generator.ts
Pourquoi faire aussi compliqué ?
Node intègre des API pour générer des chaînes de caractères aléatoires

2024-01-04 10:15 UTC, YDrogen commented on packages/backend/api/src/auth.ts
> +      res.status(401).json({ message: 'Token is not valid', error });
Il faut return ici
Si on arrive ici sans return, ça va envoyer 2 réponse, celle ci et celle en dessous

2024-01-04 10:15 UTC, YDrogen commented on packages/backend/api/src/auth.ts
> +    throw new Error(`Error validating activation code: ${String(error)}`);
Que fait cette ligne ?

2024-01-06 16:20 UTC, Mikazian commented on packages/frontend/web/src/router.tsx
corrigé

2024-01-06 16:39 UTC, Mikazian commented on packages/backend/api/src/utils/token-generator.ts
j'ai utilisé le module randomstring

2024-01-06 16:41 UTC, Mikazian commented on packages/backend/api/src/auth.ts
> +      res.status(401).json({ message: 'Token is not valid', error });
fait

2024-01-06 16:42 UTC, Mikazian commented
J'ai apporté les modifications demandées

2024-01-06 16:52 UTC, Mikazian submitted a review, later dismissed

2024-01-08 10:20 UTC, Mikazian submitted a review, later dismissed

2024-01-08 10:23 UTC, greegouze submitted a review, later dismissed

2024-01-08 21:17 UTC, Mikazian commented on packages/backend/api/package.json
> +    "randomstring": "^1.3.0"
Corrigé j'ai utilisé crypto de node

2024-01-08 21:17 UTC, Mikazian submitted a review, later dismissed

2024-01-10 11:31 UTC, greegouze approved these changes

2024-01-11 14:02 UTC, Mikazian approved these changes

2024-01-12 08:56 UTC, greegouze submitted a review, later dismissed

2024-01-12 10:49 UTC, YDrogen requested changes

2024-01-12 10:49 UTC, YDrogen commented on packages/frontend/web/src/components/auth/RegistrationForm.tsx
> +      throw new Error(`Failed to register : ${String(error)}`);
Pourquoi faire un catch si c'est pour throw dedans ? Un throw non catch va faire crash l'application !

2024-01-12 10:49 UTC, YDrogen commented on packages/backend/api/src/auth.ts
> +const FRONTEND_URL = 'http://localhost';
Y'a pas une variable d'environnement qui contient un lien un peu similaire ?
Parce que ça, ça marchera pas si c'est pas sur localhost

2024-01-12 10:49 UTC, YDrogen commented on packages/frontend/web/src/components/auth/ValidationToken.tsx
> +      throw new Error('ⓘ Token is incorrect');
Ça fait crash votre application, ça

2024-01-14 09:45 UTC, Mikazian commented on packages/frontend/web/src/components/auth/RegistrationForm.tsx
> +      throw new Error(`Failed to register : ${String(error)}`);
problème d'indentation, c'est corrigé !

2024-01-14 09:50 UTC, Mikazian commented on packages/backend/api/src/auth.ts
> +const FRONTEND_URL = 'http://localhost';
bizarre pourtant c'était passé avec la PR login

2024-01-14 09:52 UTC, Mikazian commented on packages/backend/api/src/auth.ts
> +const FRONTEND_URL = 'http://localhost';
corrigé

2024-01-14 13:09 UTC, Mikazian commented on packages/frontend/web/src/components/auth/RegistrationForm.tsx
> +      throw new Error(`Failed to register : ${String(error)}`);
code retiré

2024-01-14 13:10 UTC, Mikazian commented on packages/frontend/web/src/components/auth/RegistrationForm.tsx
> +      throw new Error(`Failed to register : ${String(error)}`);
pourquoi dans le Login.tsx s'est passé ? j'avais la même structure

2024-01-14 14:29 UTC, Mikazian commented on packages/frontend/web/src/components/auth/ValidationToken.tsx
> +      throw new Error('ⓘ Token is incorrect');
retiré

2024-01-14 16:03 UTC, greegouze approved these changes

2024-01-15 09:55 UTC, YDrogen commented on packages/frontend/web/src/components/auth/ValidationToken.tsx
> +      throw new Error('ⓘ Token is incorrect');
Ça crash toujours en cas d'erreur, y'a plus de try-catch

2024-01-15 09:55 UTC, YDrogen commented on packages/frontend/web/src/components/auth/RegistrationForm.tsx
> +      throw new Error(`Failed to register : ${String(error)}`);
Erreur de ma part, I guess

2024-01-15 10:55 UTC, Mikazian commented on packages/frontend/web/src/components/auth/RegistrationForm.tsx
> +      throw new Error(`Failed to register : ${String(error)}`);
Je vais retiré le try/catch dans le login aussi

2024-01-15 10:56 UTC, Mikazian commented on packages/backend/api/src/auth.ts
> +const FRONTEND_URL = 'http://localhost';
Du coup j'ai pris la variable d'environnement FRONTEND_HOST j'imagine que c'est ça

2024-01-16 08:25 UTC, Mikazian approved these changes

2024-01-16 23:21 UTC, greegouze approved these changes

2024-01-22 09:44 UTC, YDrogen approved these changes

2024-01-22 09:44 UTC, merged