Feature/user
WildCodeSchool/2023-09-orleans-cda-projet2-groupe-c pull request #97
Opened 2023-12-19 16:13 UTC by Mikazian

## Description

Please include a summary of the change or which issue is fixed.
- Modify migration, update type city id and city_id from user table to bigint,
- Insert in database some users,
- Insert in database users's hobbies,
- Insert in database users's languages,
- Insert in database users's technologies,
- Insert in database user's pictures.

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Area of change

- [ ] Frontend
- [x] Backend
- [ ] Other: .....

## General checklist:

- [x] My code follows the style guidelines of this project
- [x] I ran `bun run format`/`bun run lint` before commit
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation where needed
- [x] My changes generate no new warnings
- [x] I have checked my code and corrected any misspellings
- [x] I have updated `develop` and merged to my branch before submitting pull request
- [x] My pull request generate no conflicts with `develop` branch
- [x] I requested code review from other team members

## Frontend checklist:

- [ ] I followed guidelines for `HTML`/`JSX`/`Typescript`
- [ ] My `Javascript` generate no new console errors
- [ ] I tested my code cross browsers
- [ ] My slice is pixel perfect for both desktop and mobile according to design
- [ ] I conducted basic QA to assure all features are working
- [ ] I tested responsive for mobile and tablet resolutions

## Backend checklist:

- [x] I tested admin by manually adding content from zero
- [x] I created easy to use admin experience which is self-explanatory
- [x] I added description to admin fields in hard-to-understand areas
- [x] I followed guidelines for naming `Typescript` variables
- [x] I conducted basic QA to assure all features are working

2023-12-20 08:17 UTC, greegouze submitted a review, later dismissed

2023-12-20 15:30 UTC, ElBarto444 submitted a review, later dismissed
C'est ok pour moi

2023-12-20 16:28 UTC, YDrogen requested changes
Tu peux pas balancer un petit outil pour compresser toutes les images dans ton dossier ? Y'en a beaucoup qui font + de 500kb c'est énorme si elles doivent toutes être affichées sur une même page

2023-12-20 16:28 UTC, YDrogen commented on packages/backend/migrations/src/migrations/20231213190341-database-structure.ts
Hein ? Pourquoi drop `city` pour la recréer juste après ?

2023-12-20 16:28 UTC, YDrogen commented on packages/backend/forge/src/data/adminsData.json
kebab-case siouplé 🤓

2023-12-20 16:28 UTC, YDrogen commented on packages/backend/forge/src/data/usersData.json
kebab-case siouplé 🤓

2023-12-20 16:28 UTC, YDrogen commented on packages/backend/forge/src/data/usersData.json
FYI: Tu ne pourras jamais te connecter avec tous ces comptes sans bidouiller.
-> Tu peux hasher un mdp du style "password" avec l'algo et la clé que vous utilisez et mettre le hash ici partout

2023-12-23 16:05 UTC, Mikazian commented on packages/backend/migrations/src/migrations/20231213190341-database-structure.ts
Pour passer le type de l'id int4 en int8, vu qu'on a + de 35000 villes. J'avais des soucis au niveau du champ city_id lors de l'insertion d'un utilisateur. Exemple, city_id : 124567,
Je devais l'écrire comme ça : city_id: 124_567

2023-12-23 17:23 UTC, Mikazian commented on packages/backend/migrations/src/migrations/20231213190341-database-structure.ts
Je voulais change le type de l'id en int8. J'ai retiré le code

2023-12-23 17:28 UTC, Mikazian commented on packages/backend/forge/src/data/adminsData.json
fait

2023-12-23 17:28 UTC, Mikazian commented on packages/backend/forge/src/data/usersData.json
fait

2023-12-23 17:42 UTC, Mikazian commented on packages/backend/forge/src/data/usersData.json
J'ai pas trop compris l'histoire de la clef, j'ai fais un truc comme ça : 
```ruby
 const password = 'password';
        // Hash the password with bcrypt
        const hashedPassword = await Bun.password.hash(password, {
          algorithm: 'bcrypt',
          cost: 10,
        });
```

2023-12-23 18:26 UTC, Mikazian commented
J'ai baissé la résolution des images, il pèse tous moins de 200ko à part une photo à 300ko

2024-01-04 09:57 UTC, ElBarto444 submitted a review, later dismissed
C'est ok pour moi

2024-01-04 10:21 UTC, greegouze approved these changes

2024-01-04 13:18 UTC, YDrogen requested changes

2024-01-04 13:18 UTC, YDrogen commented on packages/backend/forge/src/users/insert-users.ts
> +        });
Ça peut être sorti hors de la boucle vu que c'est le même mot de passe à chaque fois

2024-01-05 13:03 UTC, Mikazian commented on packages/backend/forge/src/users/insert-users.ts
> +        });
Fait !

2024-01-07 13:36 UTC, greegouze approved these changes

2024-01-08 08:55 UTC, ElBarto444 approved these changes
C'est ok

2024-01-08 09:15 UTC, YDrogen approved these changes

2024-01-08 09:15 UTC, merged